### ISSUE TITLE
Enhancement - Addition of Pause functionality for continuous simulation

### ISSUE THREAD

**Issue by StarHime** [YPAndrew0907/Animal-Simulation-game#2]
**Is your feature request related to a problem? Please describe.**
While the continuous run simulation provides a great way to observe the dynamics of the ecosystem over time, there is currently no way to pause the simulation once it begins (unless by closing the application). 

**Describe the solution you'd like**
It would be highly advantageous to have a 'Pause' feature that allows the user to freeze the simulation at any given point in time. This could be achieved by defining another key control such as `<ARROW DOWN>` or 'P' which once pressed, would pause the ongoing continuous simulation.

This not only enhances user control over the application but also allows for a more detailed study of the ecosystem at a particular instance, which aligns well with the project's aim to "engage, learn, and enjoy nature's complexity". 

**Describe alternatives you've considered**
Another alternative could be to implement a toggle functionality on the `<ARROW UP>` key such that repetitive pressing of the arrow up key would start and pause the continuous simulation.

**Additional context**
This feature would likely require changes in the main.py module to handle the additional game event and potentially the update and render processes in the simulation.py module may need to be adapted to respect the pause state.

Looking forward to the community's thoughts on this proposed enhancement.

**Comment by YPAndrew0907** [comment]
Yes! I am indeed working on adding the world-pause feature to the game.
