### ISSUE TITLE
Need improve game operation instruction for beginner players

### ISSUE THREAD

**Issue by Slidebeen** [YPAndrew0907/Animal-Simulation-game#4]
Hello,

I a developer from China, recently find this project and try to play this game. I think it's very good simulation game, have beautiful visualisation, simulate animal life cycle is interesting. But I found a issue when I first time play this game, it's about operation instruction.

I think the operation instruction should have more detail. Now operation instruction only tell <SPACE> for run one step of simulation, <ARROW UP> for run simulation continuously. But, beginner player like me don't know what is the detail meaning of one step or run continuously when first time play. We don't know what will occur when we press these buttons, will animal move, will animal hunt or anything else? Also there no operation guide in game, beginner player maybe don't know <ARROW UP> can run simulation continuously.

So, I suggest to improve operation instruction, provide more detail, let beginner player more easy to understand and enjoy this game. If allow, I want open a pull request for this issue, try to contribute to this great project.

Thank you! Looking forward to your response 😄

**Comment by mspuiyi** [comment]
Thanks for reporting this issue and the great feedback. I agree that the current operation instructions are a bit sparse and could use more detail to help new players understand the simulation better.

Some suggestions to improve the instructions:

1. Provide a brief explanation of what each control does, e.g. "Press SPACE to advance the simulation by one step, showing how the animals move, interact, and respond to the environment." 
2. Explain the difference between running the simulation step-by-step vs continuously, and how that affects the visual experience.
3. Consider adding an in-game tooltip or popup that explains the controls when the player first starts the simulation.
4. Maybe include a short video or GIF demonstration of the controls in action to visually show new players what to expect.

These enhancements should make the game more accessible and enjoyable for beginners. I'd be happy to contribute a pull request to implement some of these improvements if that would be helpful. Let me know what you think!
